catch_rules: #转换规则
    - rule: _ #ClientWorker语法糖，匹配当前域，返回一个域名带端口
      transform_rules: #转换规则，最上面的优先最高
        - search: \#.* #在发送请求时匹配#后内容并移除
          replace: ''
        - search: \?.* #在发送请求时匹配?后内容并移除，仅限静态请求
          replace: '' 
        - search: _ 
          replace: 
          - origin.cwtc.xyz:2333 #GithubPage托管

        - search: _
          action: fetch
          fetch:
            status: 200
            engine: classic
            preflight: false
            timeout: 5000